# Generated by Django 3.1.4 on 2021-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterDjango',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=280)),
                ('image_path', models.FileField(upload_to='', verbose_name='/static/images/')),
            ],
        ),
    ]
