# Generated by Django 3.1.4 on 2021-01-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterdjango',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitterdjango',
            name='parent_tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdjango',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
