# Generated by Django 3.1.4 on 2021-03-06 15:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210104_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdjango',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        )
    ]
