# Generated by Django 3.1.4 on 2021-03-06 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210306_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdjango',
            name='image_path',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
